paths:
  static: ''
  uploads: uploads
timezone: Asia/Kolkata
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  icons:
    path: icons
    icon: ios
